version: '{build}-{branch}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_folder: c:\projects\microorm.dapper.repositories
services: mssql2014
install:
- cmd: 
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  verbosity: normal
after_build:
- ps: >-
    cd MicroOrm.Dapper.Repositories

    dotnet pack -c Release --no-build
test_script:
- ps: >-
    cd ../MicroOrm.Dapper.Repositories.Tests

    dotnet test
artifacts:
- path: '**\*.nupkg'
  name: All Nupkg
deploy:
- provider: NuGet
  api_key:
    secure: cFZluW3B8EOB1rgZe1z9JSNSuEdNOfH0W2ZSMsrX16qoorzXiobCpN7BpJtyk2rR
  skip_symbols: false
  artifact: '**\*.nupkg'
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - sergey.kuznetsov@hotmail.com
  subject: 'Build: MicroOrm.Dapper.Repositories'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true